=== MathisBicheyre/TP1-XML/--EXO_2/contacts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- Category -->
	<xs:element name="category">
		<xs:simpleType>
    		<xs:restriction base="xs:string">
      			<xs:enumeration value="Person"/>
      			<xs:enumeration value="Company"/>
    		</xs:restriction>
  		</xs:simpleType>
	</xs:element>
	
	<!-- Name -->
	<xs:element name="name" type="xs:string"/>
	
	<!-- Surname -->
	<xs:element name="surname" type="xs:string"/>
	
	<!-- Phone number -->
	<xs:element name="number">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="type" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>		
		</xs:complexType>
	</xs:element>
	
	<!-- Phone numbers -->
	<xs:element name="pnumbers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="number" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- Street, Zipcode, City, Country -->
	<xs:element name="street">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="number" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>		
		</xs:complexType>
	</xs:element>
	<xs:element name="zipcode" type="xs:string"/>
	<xs:element name="city" type="xs:string"/>
	<xs:element name="country" type="xs:string"/>
	
	<!-- Address -->
	<xs:element name="address">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="street"/>
				<xs:element ref="city"/>
				<xs:element ref="zipcode"/>
				<xs:element ref="country"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- Contact -->
	<xs:element name="contact">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="category"/>
				<xs:element ref="name"/>
				<xs:element ref="surname" minOccurs="0"/>
				<xs:element ref="pnumbers"/>
				<xs:element ref="address"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- Root Element -->
	<xs:element name="contacts">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="contact" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== MathisBicheyre/TP1-XML/--EXO_2/contacts.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Fri Oct 18 08:54:58 CEST 2019 -->


<contacts xsi:noNamespaceSchemaLocation="contacts.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<contact>
		<category>Person</category>
		<name>
		
			Dutronc
		
		</name>
		<surname>

			Paul

		</surname>
		<pnumbers>
			<number type="mobile">

				0612345678

			</number>
		</pnumbers>
		<address>
			<street number="12">

				Rue du Pont

			</street>
			<city>

				Paris

			</city>
			<zipcode>

				750111

			</zipcode>
			<country>

				FR

			</country>
		</address>
	</contact>
</contacts>
