=== MathisBicheyre/TP1-XML/--EXO_1/movies.dtd
<!ELEMENT movies  ( movie+ )>

<!-- <!ELEMENT movie  ( title , genre , duration , author , language , actors , year , ratings? , description , showings )>
 -->

<!ELEMENT movie ANY>

<!ELEMENT title  ( #PCDATA )>

<!ELEMENT genre  ( #PCDATA )>

<!ELEMENT duration  ( #PCDATA )>

<!ELEMENT author  ( #PCDATA )>

<!ELEMENT language  ( #PCDATA )>

<!ELEMENT actors  ( actor+ )>

<!ELEMENT actor  ( #PCDATA )>

<!ELEMENT year  ( #PCDATA )>

<!ELEMENT ratings  ( prating? , srating? )>

<!ELEMENT prating  ( #PCDATA )>

<!ELEMENT srating  ( #PCDATA )>

<!ELEMENT description  ( #PCDATA )>

<!ELEMENT showings  ( projection+ )>

<!ELEMENT projection  ( days , hours )>

<!ELEMENT days  ( day+ )>

<!ELEMENT day  ( #PCDATA )>

<!ELEMENT hours  ( hour+ )>

<!ELEMENT hour  ( #PCDATA )>

=== MathisBicheyre/TP1-XML/--EXO_1/movies.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Fri Oct 18 08:04:49 CEST 2019 -->

<!DOCTYPE movies SYSTEM "movies.dtd">

<movies>
	<movie>
		<title>
			Les naufragés de l'île aux pirates
		</title>
		<genre>
			Aventure
		</genre>
		<duration>
			1h32min
		</duration>
		<author>
			Nils Gaup
		</author>
		<language>
			VF
		</language>
		<actors>
			<actor>
				Stian Smestad
			</actor>
			<actor>
				Gabriel Byrne
			</actor>
			<actor>
				Louisa Milwood-Haigh
			</actor>
		</actors>
		<year>
			1990
		</year>
		<ratings>
			<prating>
				3/5
			</prating>
			<srating>
				3/5
			</srating>
		</ratings>
		<description>
			A young Norwegian boy in 1850s England goes to work as a cabin boy and discovers some of his shipmates are actually pirates. 
		</description>
		<showings>
			<projection>
				<days>
					<day>
						Wed
					</day>
					<day>
						Sat
					</day>
				</days>
				<hours>
					<hour>
						14:00
					</hour>
					<hour>
						16:40
					</hour>
					<hour>
						19:40
					</hour>
					<hour>
						22:10
					</hour>
				</hours>
			</projection>
			<projection>
				<days>
					<day>
						Tue
					</day>
					<day>
						Fri
					</day>
					<day>
						Mon
					</day>
					<day>
						Thu
					</day>
				</days>
				<hours>
					<hour>
						14:00
					</hour>
					<hour>
						19:40
					</hour>
					<hour>
						22:10
					</hour>
				</hours>
			</projection>
			<projection>
				<days>
					<day>
						Sun
					</day>
				</days>
				<hours>
					<hour>
						10:20
					</hour>
					<hour>
						14:00
					</hour>
					<hour>
						16:40
					</hour>
					<hour>
						20:20
					</hour>
				</hours>
			</projection>
		</showings>
	</movie>
	
	<movie>
		<title>
			Les Brigades du Tigre
		</title>
		<genre>
			Thriller
		</genre>
		<duration>
			2h05min
		</duration>
		<author>
			Jérôme Cornuau
		</author>
		<language>
			VF
		</language>
		<actors>
			<actor>
				C. Cornillac
			</actor>
			<actor>
				D. Kruger
			</actor>
			<actor>
				E. Baer
			</actor>
		</actors>
		<year>
			2005
		</year>
		<ratings>
			<prating>
				3/5
			</prating>
			<srating>
				4/5
			</srating>
		</ratings>
		<description>
			About the  adventures of commissar Valentin and inspectors Terrasson and Pujol, members of the " Brigades mobiles", special squad of the French  police before the first world war..
		</description>
		<showings>
			<projection>
				<days>
					<day>
						Wed
					</day>
					<day>
						Sat
					</day>
				</days>
				<hours>
					<hour>
						14:00
					</hour>
					<hour>
						16:40
					</hour>
					<hour>
						19:40
					</hour>
					<hour>
						22:10
					</hour>
				</hours>
			</projection>
			<projection>
				<days>
					<day>
						Tue
					</day>
					<day>
						Fri
					</day>
					<day>
						Mon
					</day>
					<day>
						Thu
					</day>
				</days>
				<hours>
					<hour>
						14:00
					</hour>
					<hour>
						19:40
					</hour>
					<hour>
						22:10
					</hour>
				</hours>
			</projection>
			<projection>
				<days>
					<day>
						Sun
					</day>
				</days>
				<hours>
					<hour>
						10:20
					</hour>
					<hour>
						14:00
					</hour>
					<hour>
						16:40
					</hour>
					<hour>
						20:20
					</hour>
				</hours>
			</projection>
		</showings>
	</movie>
	
	<movie>
		<title>
			Rencontres du troisième type
		</title>
		<genre>
			Drama
		</genre>
		<duration>
			2h18min
		</duration>
		<author>
			Steven Spielberg
		</author>
		<language>
			OV
		</language>
		<actors>
			<actor>
				Richard Dreyfuss
			</actor>
			<actor>
				François Truffaut
			</actor>
			<actor>
				Teri Garr
			</actor>
		</actors>
		<year>
			1977
		</year>
		<ratings>
			<prating>
				5/5
			</prating>
			<srating>
				4/5
			</srating>
		</ratings>
		<description>
			Roy Neary, an electric lineman, watches how his quiet and ordinary daily life turns upside down after a close encounter with a UFO. 
		</description>
		<showings>
			<projection>
				<days>
					<day>
						Wed
					</day>
					<day>
						Sat
					</day>
				</days>
				<hours>
					<hour>
						14:00
					</hour>
					<hour>
						16:40
					</hour>
					<hour>
						19:40
					</hour>
					<hour>
						22:10
					</hour>
				</hours>
			</projection>
			<projection>
				<days>
					<day>
						Tue
					</day>
					<day>
						Fri
					</day>
					<day>
						Mon
					</day>
					<day>
						Thu
					</day>
				</days>
				<hours>
					<hour>
						14:00
					</hour>
					<hour>
						19:40
					</hour>
					<hour>
						22:10
					</hour>
				</hours>
			</projection>
			<projection>
				<days>
					<day>
						Sun
					</day>
				</days>
				<hours>
					<hour>
						10:20
					</hour>
					<hour>
						14:00
					</hour>
					<hour>
						16:40
					</hour>
					<hour>
						20:20
					</hour>
				</hours>
			</projection>
		</showings>
	</movie>
	
	<movie>
		<title>
			Evil Dead
		</title>
		<genre>
			Horror
		</genre>
		<duration>
			1h25min
		</duration>
		<author>
			Sam Raimi
		</author>
		<language>
			OV
		</language>
		<actors>
			<actor>
				Bruce Campbell
			</actor>
			<actor>
				Ellen Sandweiss
			</actor>
			<actor>
				Richard DeManincor
			</actor>
		</actors>
		<year>
			1981
		</year>
		<ratings>
			<prating>
				4/5
			</prating>
			<srating>
				4/5
			</srating>
		</ratings>
		<description>
			Five friends travel to a cabin in the woods, where they unknowingly release flesh-possessing demons. 
		</description>
		<showings>
			<projection>
				<days>
					<day>
						Wed
					</day>
					<day>
						Sat
					</day>
				</days>
				<hours>
					<hour>
						14:00
					</hour>
					<hour>
						16:40
					</hour>
					<hour>
						19:40
					</hour>
					<hour>
						22:10
					</hour>
				</hours>
			</projection>
			<projection>
				<days>
					<day>
						Tue
					</day>
					<day>
						Fri
					</day>
					<day>
						Mon
					</day>
					<day>
						Thu
					</day>
				</days>
				<hours>
					<hour>
						14:00
					</hour>
					<hour>
						19:40
					</hour>
					<hour>
						22:10
					</hour>
				</hours>
			</projection>
			<projection>
				<days>
					<day>
						Sun
					</day>
				</days>
				<hours>
					<hour>
						10:20
					</hour>
					<hour>
						14:00
					</hour>
					<hour>
						16:40
					</hour>
					<hour>
						20:20
					</hour>
				</hours>
			</projection>
		</showings>
	</movie>
	
	<movie>
		<title>
			A Star Is Born
		</title>
		<genre>
			Romance
		</genre>
		<duration>
			2h16min
		</duration>
		<author>
			Bradley Cooper
		</author>
		<language>
			OV
		</language>
		<actors>
			<actor>
				Lady Gaga
			</actor>
			<actor>
				Bradley Cooper
			</actor>
			<actor>
				Sam Elliott
			</actor>
		</actors>
		<year>
			2018
		</year>
		<ratings>
			<prating>
				4/5
			</prating>
			<srating>
				4/5
			</srating>
		</ratings>
		<description>
			A musician helps a young singer find fame as age and alcoholism send his own career into a downward spiral. 
		</description>
		<showings>
			<projection>
				<days>
					<day>
						Wed
					</day>
					<day>
						Sat
					</day>
				</days>
				<hours>
					<hour>
						14:00
					</hour>
					<hour>
						16:40
					</hour>
					<hour>
						19:40
					</hour>
					<hour>
						22:10
					</hour>
				</hours>
			</projection>
			<projection>
				<days>
					<day>
						Tue
					</day>
					<day>
						Fri
					</day>
					<day>
						Mon
					</day>
					<day>
						Thu
					</day>
				</days>
				<hours>
					<hour>
						14:00
					</hour>
					<hour>
						19:40
					</hour>
					<hour>
						22:10
					</hour>
				</hours>
			</projection>
			<projection>
				<days>
					<day>
						Sun
					</day>
				</days>
				<hours>
					<hour>
						10:20
					</hour>
					<hour>
						14:00
					</hour>
					<hour>
						16:40
					</hour>
					<hour>
						20:20
					</hour>
				</hours>
			</projection>
		</showings>
	</movie>
	
	<movie>
		<title>
			Halloween, la nuit des masques
		</title>
		<genre>
			Horror
		</genre>
		<duration>
			1h31min
		</duration>
		<author>
			John Carpenter
		</author>
		<language>
			OV
		</language>
		<actors>
			<actor>
				Donald Pleasence
			</actor>
			<actor>
				Jamie Lee Curtis
			</actor>
			<actor>
				Tony Moran
			</actor>
		</actors>
		<year>
			1978
		</year>
		<ratings>
			<prating>
				5/5
			</prating>
			<srating>
				4/5
			</srating>
		</ratings>
		<description>
			Fifteen years after murdering his sister on Halloween night 1963, Michael Myers escapes from a mental hospital and returns to the small town of Haddonfield, Illinois to kill again. 
		</description>
		<showings>
			<projection>
				<days>
					<day>
						Wed
					</day>
					<day>
						Sat
					</day>
				</days>
				<hours>
					<hour>
						14:00
					</hour>
					<hour>
						16:40
					</hour>
					<hour>
						19:40
					</hour>
					<hour>
						22:10
					</hour>
				</hours>
			</projection>
			<projection>
				<days>
					<day>
						Tue
					</day>
					<day>
						Fri
					</day>
					<day>
						Mon
					</day>
					<day>
						Thu
					</day>
				</days>
				<hours>
					<hour>
						14:00
					</hour>
					<hour>
						19:40
					</hour>
					<hour>
						22:10
					</hour>
				</hours>
			</projection>
			<projection>
				<days>
					<day>
						Sun
					</day>
				</days>
				<hours>
					<hour>
						10:20
					</hour>
					<hour>
						14:00
					</hour>
					<hour>
						16:40
					</hour>
					<hour>
						20:20
					</hour>
				</hours>
			</projection>
		</showings>
	</movie>
</movies>
